JUnit version 4.12
.E
Time: 0.294
There was 1 failure:
1) test0(org.joda.time.field.PreciseDurationDateTimeField_ESTest)
org.joda.time.IllegalFieldValueException: Value 604800 for dayOfMonth must be in the range [1,31]
	at org.joda.time.field.FieldUtils.verifyValueBounds(FieldUtils.java:220)
	at org.joda.time.field.PreciseDurationDateTimeField.set(PreciseDurationDateTimeField.java:78)
	at org.joda.time.chrono.GJChronology$CutoverField.set(GJChronology.java:732)
	at org.joda.time.chrono.BaseChronology.getDateTimeMillis(BaseChronology.java:134)
	at org.joda.time.chrono.AssembledChronology.getDateTimeMillis(AssembledChronology.java:136)
	at org.joda.time.chrono.LimitChronology.getDateTimeMillis(LimitChronology.java:188)
	at org.joda.time.chrono.AssembledChronology.getDateTimeMillis(AssembledChronology.java:133)
	at org.joda.time.field.PreciseDurationDateTimeField_ESTest.test0(PreciseDurationDateTimeField_ESTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

FAILURES!!!
Tests run: 1,  Failures: 1

